# Generated by Django 4.0.6 on 2022-07-30 13:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VisitorLetters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=75)),
                ('message', models.TextField(max_length=1024)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Писмо от пользователя',
                'verbose_name_plural': 'Письма от пользвателей',
            },
        ),
        migrations.CreateModel(
            name='MailingLetters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=75)),
                ('message', models.TextField(max_length=1024)),
                ('is_send', models.CharField(choices=[('SEND', 'Отправить'), ('Draft', 'Черновик')], help_text='Отправлять или в черновик', max_length=255, verbose_name='Состояние письма')),
                ('users', models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='Отправка пользователям')),
            ],
            options={
                'verbose_name': 'Писмьо админа',
                'verbose_name_plural': 'Письма админа',
            },
        ),
    ]
