# Generated by Django 4.0.6 on 2022-07-28 17:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gym',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.PositiveIntegerField(choices=[(1, 'месяц'), (2, '2 месяца'), (3, '3 месяца'), (6, 'пол года'), (12, 'год')], default=1, verbose_name='Колличество месяцев')),
                ('data_start', models.DateTimeField(auto_now_add=True, verbose_name='Дата покупки')),
                ('data_end', models.DateTimeField(default=datetime.datetime(2022, 7, 28, 21, 47, 25, 204260), verbose_name='Дата окончания ')),
                ('price', models.CharField(blank=True, default='', help_text='Месяц - 1000.                                       2 Месяца - 1800.                                       3 Месяца - 2500.                                       Пол года - 4000.                                       Год - 8000.', max_length=255, verbose_name='Цена')),
            ],
            options={
                'verbose_name': 'Абонимент в зал',
                'verbose_name_plural': 'Абонименты в зал',
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(verbose_name='Порядковый номер')),
                ('category', models.CharField(choices=[('Suite', 'Сюит'), ('Apartment', 'Апартамент '), ('Lux', 'Люкс '), ('Junior Suite', 'Джуниор Сюит'), ('Studio', 'Студия'), ('Standard', 'стандарт')], default='Standard', max_length=255, verbose_name='Категория номера')),
                ('price', models.DecimalField(blank=True, decimal_places=2, default=1, max_digits=8, verbose_name='Цена за ночь')),
                ('number_of_places', models.PositiveSmallIntegerField(verbose_name='Колличество мест')),
                ('free', models.BooleanField(default=True, help_text='True - в номере никто не проживаетFalse - на данный момент номер занят', verbose_name='Занятость')),
            ],
            options={
                'verbose_name': 'Номер',
                'verbose_name_plural': 'Номера',
            },
        ),
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adult', models.BooleanField(help_text='True - гость достиг совершенолетия. False - гость не достиг совершенолетия', verbose_name='Совершенолетие')),
                ('numbers_passport', models.PositiveIntegerField(verbose_name='Номер паспорта')),
                ('in_hotel', models.BooleanField(default=False, verbose_name='Проживает ли на данный момент')),
                ('check_in_time', models.DateTimeField(auto_now_add=True, verbose_name='Врея заселения')),
                ('eviction_time', models.DateTimeField(blank=True, default=None, null=True, verbose_name='Время выселения')),
                ('gym', models.ManyToManyField(blank=True, related_name='related_visitor', to='hotel.gym', verbose_name='Абонимент в спортзал')),
                ('number_room', models.ManyToManyField(blank=True, to='hotel.room', verbose_name='Номер проживания')),
            ],
            options={
                'verbose_name': 'Посетител',
                'verbose_name_plural': 'Посетители',
            },
        ),
    ]
