# Generated by Django 4.0.6 on 2022-08-03 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='free',
        ),
        migrations.RemoveField(
            model_name='room',
            name='visitors',
        ),
        migrations.AlterField(
            model_name='gym',
            name='data_end',
            field=models.DateTimeField(verbose_name='Дата окончания '),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='last_name',
            field=models.CharField(max_length=255, verbose_name='Фамилия пользователя'),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='numbers_passport',
            field=models.PositiveBigIntegerField(default=1, verbose_name='Номер паспорта'),
            preserve_default=False,
        ),
    ]
