# Generated by Django 4.0.6 on 2022-07-28 17:52

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hotel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gym',
            name='visitor',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='related_gum', to='hotel.visitor', verbose_name='Гость'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='room',
            name='visitors',
            field=models.ManyToManyField(blank=True, to='hotel.visitor', verbose_name='Гости в номере'),
        ),
        migrations.AddField(
            model_name='visitor',
            name='online_client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Онлайн аккаунт'),
        ),
        migrations.AlterField(
            model_name='gym',
            name='data_end',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 28, 21, 52, 25, 166342), verbose_name='Дата окончания '),
        ),
    ]
