# Generated by Django 4.0.6 on 2022-08-02 13:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gym',
            name='data_end',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 2, 17, 28, 0, 902591), verbose_name='Дата окончания '),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='numbers_passport',
            field=models.PositiveBigIntegerField(default=1, verbose_name='Номер паспорта'),
            preserve_default=False,
        ),
    ]
