# Generated by Django 4.0.6 on 2022-07-28 17:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0002_gym_visitor_room_visitors_visitor_online_client_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gym',
            name='data_end',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 28, 21, 53, 34, 901692), verbose_name='Дата окончания '),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='check_in_time',
            field=models.DateField(auto_now_add=True, verbose_name='Врея заселения'),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='eviction_time',
            field=models.DateField(blank=True, default=None, null=True, verbose_name='Время выселения'),
        ),
    ]
