# Generated by Django 4.0.6 on 2022-08-02 13:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0002_alter_gym_data_end_alter_visitor_numbers_passport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gym',
            name='data_end',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 2, 17, 35, 3, 137095), verbose_name='Дата окончания '),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='last_name',
            field=models.CharField(max_length=255, verbose_name='Фамилия пользователя'),
        ),
    ]
