# Generated by Django 4.0.6 on 2022-08-02 15:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0003_alter_gym_data_end_alter_visitor_last_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='free',
        ),
        migrations.RemoveField(
            model_name='room',
            name='visitors',
        ),
        migrations.AlterField(
            model_name='gym',
            name='data_end',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 2, 19, 51, 53, 634993), verbose_name='Дата окончания '),
        ),
    ]
