# Generated by Django 4.0.6 on 2022-07-29 10:45

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0004_alter_gym_data_end_alter_visitor_in_hotel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gym',
            name='data_end',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 29, 14, 45, 29, 369437), verbose_name='Дата окончания '),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='number_room',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='hotel.room', verbose_name='Номер проживания'),
        ),
    ]
