# Generated by Django 4.0.6 on 2022-07-29 10:51

import datetime
from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0005_alter_gym_data_end_alter_visitor_number_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitor',
            name='first_name',
            field=models.CharField(default=None, max_length=255, verbose_name='Имя пользователя'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='visitor',
            name='last_name',
            field=models.CharField(db_index=True, default=None, max_length=255, verbose_name='Фамилия пользователя'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='visitor',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(default=None, max_length=255, region=None, verbose_name='Номер телефона'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='gym',
            name='data_end',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 29, 14, 50, 46, 707700), verbose_name='Дата окончания '),
        ),
    ]
