# Generated by Django 4.0.6 on 2022-08-13 11:11

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0006_rename_reviews_review_alter_visitor_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitor',
            name='first_name',
            field=models.CharField(max_length=255, verbose_name='Имя пользователя'),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='last_name',
            field=models.CharField(max_length=255, verbose_name='Фамилия пользователя'),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=255, region=None, verbose_name='Номер телефона'),
        ),
    ]
