# Generated by Django 4.0.6 on 2022-07-29 17:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0009_alter_gym_data_end_remove_visitor_gym_visitor_gym'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gym',
            name='data_end',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 29, 21, 31, 22, 521848), verbose_name='Дата окончания '),
        ),
        migrations.RemoveField(
            model_name='visitor',
            name='gym',
        ),
        migrations.AddField(
            model_name='visitor',
            name='gym',
            field=models.ManyToManyField(blank=True, related_name='related_visitor', to='hotel.gym', verbose_name='Абонимент в спортзал'),
        ),
    ]
