# Generated by Django 4.0.6 on 2022-07-30 11:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0010_alter_gym_data_end_remove_visitor_gym_visitor_gym'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gym',
            name='data_end',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 30, 15, 4, 8, 726844), verbose_name='Дата окончания '),
        ),
    ]
