# Generated by Django 4.0.6 on 2022-07-30 13:13

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hotel', '0011_alter_gym_data_end'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gym',
            name='data_end',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 30, 17, 13, 7, 956899), verbose_name='Дата окончания '),
        ),
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(max_length=1024, verbose_name='Тело текста отзыва')),
                ('file', models.FileField(blank=True, null=True, upload_to='reviews/%Y/%m /%d /', verbose_name='Прикрепленный файл к отзыву')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время создания отзыва')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Время последнего обновления отзыва')),
                ('active', models.BooleanField(default=True, verbose_name='Состояние отзыва')),
                ('rating', models.CharField(blank=True, choices=[('1', 'terribly'), ('2', 'bad'), ('3', 'ok'), ('4', 'good'), ('5', 'amazing')], max_length=25, null=True, verbose_name='Рейтинг отеля')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Автор отзыва')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
            },
        ),
    ]
