# Generated by Django 4.0.6 on 2022-07-30 13:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0012_alter_gym_data_end_reviews'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gym',
            name='data_end',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 30, 17, 38, 55, 891693), verbose_name='Дата окончания '),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='reviews/%Y/%m/%d/', verbose_name='Прикрепленный файл к отзыву'),
        ),
    ]
